name: lemur

services:

  postgres:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lemur
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - postgres
    volumes:
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lemur"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: apache/kafka:4.2.0
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:49092
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:49092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092,CONTROLLER://kafka:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka_data:/var/lib/kafka/data:rw
    networks:
      - kafka
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka-init-job:
    image: apache/kafka:4.2.0
    entrypoint: /bin/bash
    networks:
      - kafka
    depends_on:
      kafka:
        condition: service_healthy
    command: |
      -c "
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic lemur --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092
      "

  #
  # Apps Profile
  #

  lemur-flyway:
    image: "lemur-flyway:${LEMUR_VERSION:-snapshot}"
    profiles:
      - apps
      - monitoring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lemur
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  lemur-app:
    image: "lemur-app:${LEMUR_VERSION:-snapshot}"
    profiles:
      - apps
      - monitoring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lemur
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "127.0.0.1:8321:8080"
    networks:
      - postgres
      - kafka
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      lemur-flyway:
        condition: service_completed_successfully

  #
  # Monitoring Profile
  #

  prometheus:
    image: prom/prometheus:v3.10.0
    profiles:
      - monitoring
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./conf/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
    depends_on:
      lemur-app:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- -q http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  loki:
    image: grafana/loki:3.6
    profiles:
      - monitoring
    volumes:
      - ./conf/loki/loki.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  promtail:
    image: grafana/promtail:3.6
    profiles:
      - monitoring
    volumes:
      - ./conf/promtail/promtail.yaml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- -q http://localhost:9080/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grafana:
    image: grafana/grafana:12.3
    profiles:
      - monitoring
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: postgres
      GF_DATABASE_SSL_MODE: disable
    volumes:
      - ./conf/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./conf/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - monitoring
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- -q http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  kafka:
  postgres:
  monitoring:

volumes:
  kafka_data:
  postgres_data:
  prometheus_data:
  loki_data:
